name: Shell Script Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Shell Script
        run: bash newinstall.sh
